[32m2022-08-05 12:00:31 -0500[0m - dagster - [34mDEBUG[0m - say_hello_job - 4f1bc6d5-932a-4cd5-8050-8d69308dcafb - 1968884 - hello - LOGS_CAPTURED - Started capturing logs for step: hello.
[32m2022-08-05 12:00:31 -0500[0m - dagster - [34mDEBUG[0m - say_hello_job - 4f1bc6d5-932a-4cd5-8050-8d69308dcafb - 1968884 - hello - STEP_START - Started execution of step "hello".
[32m2022-08-05 12:00:31 -0500[0m - dagster - [34mERROR[0m - [31msay_hello_job - 4f1bc6d5-932a-4cd5-8050-8d69308dcafb - 1968884 - hello - STEP_FAILURE - Execution of step "hello" failed.

dagster.core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "hello"::

TypeError: str() argument 'encoding' must be str, not int

Stack Trace:
  File "/home/fils/.local/lib/python3.10/site-packages/dagster/core/execution/plan/utils.py", line 47, in solid_execution_error_boundary
    yield
  File "/home/fils/.local/lib/python3.10/site-packages/dagster/utils/__init__.py", line 398, in iterate_with_context
    next_output = next(iterator)
  File "/home/fils/.local/lib/python3.10/site-packages/dagster/core/execution/plan/compute_generator.py", line 65, in _coerce_solid_compute_fn_to_iterator
    result = fn(context, **kwargs) if context_arg_provided else fn(**kwargs)
  File "/home/fils/src/Projects/gleaner.io/scheduler/python/dagster/gleaner/gleaner/ops/hello.py", line 16, in hello
    r = str('returned value:', returned_value)
[0m
